name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build_and_test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean Workspace
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/Caches/org.swift.swiftpm

      - name: Reset Simulators
        run: xcrun simctl shutdown all && xcrun simctl erase all

      - name: Setup Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run Tests
        run: bundle exec fastlane test --verbose
