name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]



jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ciaranmul/swiftlintdocker:v0.51.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 11

      - name: Generate SSH Key for Repository Access
        run: |
          ssh-keygen -t rsa -b 4096 -C "github-actions@github.com" -f ~/.ssh/id_rsa -N ""
          echo "Host github.com\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no" > ~/.ssh/config

      - name: Add Public Key to Known Hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup SwiftLint Configuration Submodule
        run: git submodule update --init --recursive

      - name: Lint Project
        run: |
          swiftlint lint --reporter html | tee swiftlint.result.html

      - name: Upload Lint Results
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: swiftlint.result.html

  build_and_test:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 11

      - name: Generate SSH Key for Repository Access
        run: |
          ssh-keygen -t rsa -b 4096 -C "github-actions@github.com" -f ~/.ssh/id_rsa -N ""
          echo "Host github.com\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no" > ~/.ssh/config

      - name: Add Public Key to Known Hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Merge Base Branch
        run: |
          git merge origin/$(bash scripts/get_base_branch.sh) --ff-only

      - name: Restore Cached Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: gem-cache-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            gem-cache-${{ runner.os }}-${{ github.ref_name }}
            gem-cache-${{ runner.os }}

      - name: Bootstrap Environment
        run: ./scripts/bootstrap_circle.sh

      - name: Save Cached Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: gem-cache-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('Gemfile.lock') }}

      - name: Run Tests
        run: bundle exec fastlane ios test

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: fastlane/test_output/report.html

      - name: Upload Scan Logs
        uses: actions/upload-artifact@v3
        with:
          name: scan-logs
          path: ~/Library/Logs/scan
