name: Lint with SwiftLint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ciaranmul/swiftlintdocker:v0.51.0

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

    

      # Step 3: Update Submodules
      - name: Setup SwiftLint Configuration Submodules
        run: git submodule update --init --recursive

      # Step 4: Lint Project
      - name: Lint Project
        run: swiftlint lint --reporter html | tee swiftlint.result.html

      # Step 5: Upload Lint Results as Artifacts
      - name: Upload Lint Results
        uses: actions/upload-artifact@v3
        with:
          name: Lint-Results
          path: swiftlint.result.html
