name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]







jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 11

      - name: Generate SSH Key for Repository Access
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 4096 -C "github-actions@github.com" -f ~/.ssh/id_rsa -N ""
          echo "Host github.com\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no" > ~/.ssh/config

      - name: Add Public Key to Known Hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Output Public Key
        run: |
          echo "Add the following public key to GitHub as a deploy key:" 
          cat ~/.ssh/id_rsa.pub

      - name: Clone logging-ios Repository
        run: |
          git clone git@github.com:ssar-1/Ghteam.git
          git clone git@github.com:ssar1/ghteam.git
          
      - name: Setup SwiftLint Configuration Submodule
        run: git submodule update --init --recursive

      - name: Lint Project
        run: |
          swiftlint lint --reporter html | tee swiftlint.result.html

      - name: Upload Lint Results
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: swiftlint.result.html


